# Generated by Django 5.2.15 on 2026-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('photo', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
